# https://docs.haskellstack.org/en/stable/travis_ci/

language: generic
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

addons:
  apt:
    packages:
      - libgmp-dev
      - llvm-9-tools
      - llvm-9-dev
      - python3-pip
      - python3-setuptools
      - haskell-stack
  homebrew:
    update: true
    package:
      - llvm@9
      - haskell-stack

os:
  - linux
  - osx

dist: bionic

script:
  - export DIR=~/.local/bin
  - export PATH=$HOME/.local/bin:/usr/lib/llvm-9/bin:$PATH
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=$(brew --prefix llvm@9)/bin:$PATH; fi
  - if [ ! -d "$DIR" ]; then mkdir -p $DIR; fi
  - stack upgrade
  - hash -r
  - stack setup
  - pip3 install --upgrade numpy
  - make tests
