name: Haskell tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, safe-names-dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        include:
          - os: macos-latest
            install_deps: brew install llvm@12 pkg-config wget gzip
            path_extension: $(brew --prefix llvm@12)/bin
          - os: ubuntu-20.04
            install_deps: sudo apt-get install llvm-12-tools llvm-12-dev pkg-config wget gzip
            path_extension: /usr/lib/llvm-12/bin

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Haskell Stack
      uses: actions/setup-haskell@v1
      with:
        enable-stack: true
        stack-no-global: true
        stack-version: 'latest'

    - name: Install system dependencies
      run: |
        ${{ matrix.install_deps }}
        echo "${{ matrix.path_extension }}" >> $GITHUB_PATH

    - name: Get example files
      run: |
        wget http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz
        wget http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-labels-idx1-ubyte.gz
        gunzip t10k-images-idx3-ubyte.gz t10k-labels-idx1-ubyte.gz
        mv t10k-images-idx3-ubyte t10k-labels-idx1-ubyte $GITHUB_WORKSPACE/examples/

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          $GITHUB_WORKSPACE/.stack-work
          $GITHUB_WORKSPACE/examples/t10k-images-idx3-ubyte
          $GITHUB_WORKSPACE/examples/t10k-labels-idx1-ubyte

        key: ${{ runner.os }}-v5-${{ hashFiles('**/*.cabal', 'stack*.yaml') }}
        restore-keys: ${{ runner.os }}-v5-

    # This step is a workaround.
    # See issue for context: https://github.com/actions/cache/issues/445
    - name: Remove cached Setup executables
      run: rm -rf ~/.stack/setup-exe-cache
      if: runner.os == 'macOS'

    - name: Build, treating warnings as errors
      run: make build-ci
      if: runner.os == 'Linux'

    - name: Build
      run: make build

    - name: Run tests
      run: make tests
